### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by slumki** [nbuytaert1/apex-live-validation#11]
Hello Nick.
Your plugins are awesome, thank you very much for building them. They're all great, and improve Oracle APEX significantly. Great usability! Once I understand better Oracle APEX, it'll be a pleasure to contribute with nice plugins to the community too.

I'd like to know about your plugins licensing. Since they're GPL, I'd like to know if a software built using one of your plugins will need to be necessarily open-source (GPL'd) too - in other words, if it's or not  possible to use in a public website, for example, but without sharing the website APEX export script and other source codes.

In the case of it being possible, I'd like to know if it wouldn't be an alternative to release the plugins with dual-license with a more permissive license (something like GPL and MIT, or GPL and BSD).

Thank you very much.

**Comment by nbuytaert1** [comment]
You can use all of my APEX plugins in both public and private websites. Even commercial ones are allowed. I am not a big expert in software licensing, but I thought that the GPL license covered all of my concerns. Anyway, don't worry too much about the licensing part of the plugins. I can assure you that all of my plugins are absolutely free to use.
