### ISSUE TITLE
Plug In does not work under Apex 5 EA3

### ISSUE THREAD

**Issue by cjs** [nbuytaert1/apex-live-validation#12]
There is a javascript syntax error when using this plugin under Apex 5 EA3. For example:

https://apexea.oracle.com/pls/apex/f?p=12092:2

Look in the browser console. I suspect this is because jQuery was updated to 2.1.3 and there is an incompatibility.

**Comment by cjs** [comment]
More information. I believe what is happening is due to the jQuery upgrade to 2.1.3. 

In my test, the function that gets rendered is:

```javascript
apex.da.initDaEventList = function(){
apex.da.gEventList = [
{"bindEventType":"ready",actionList:[{"eventResult":true,"executeOnPageInit":false,"stopExecutionOnError":true,javascriptFunction:
    function() {
      var render = this;
      var action = render.action;
      var l_allowWhitespace = true;

      if (!action.attribute14) { action.attribute14 = ""; }

      if (action.attribute01 !== "form") {
        // item validation
        if (action.attribute01 === "notBlank") {
          action.attribute01 = "notEmpty";
          l_allowWhitespace = false;
        }
        if (!action.attribute04) { action.attribute04 = ""; }
        if (!action.attribute10) { action.attribute10 = ""; }
        if (!action.attribute11) { action.attribute11 = ""; }

        $(action.attribute02).alv({
          validate: action.attribute01,
          triggeringEvent: action.attribute03,
          condition: action.attribute04,
          errorMsg: action.attribute14,
          errorMsgLocation: action.attribute15,
          allowWhitespace: l_allowWhitespace,
          itemType: action.attribute06,
          dateFormat: "DD-MON-RR",
          min: action.attribute10,
          max: action.attribute11,
          equal: action.attribute12,
          regex: action.attribute13
        });
      } else {
        // form validation
        $(action.attribute07).alv("validateForm", {
          formsToSubmit: action.attribute05,
          errorMsg: action.attribute14
        });
      }
    }
  ,"attribute01":"notEmpty","attribute02":"#P2_TEST_ITEM,","attribute03":"blur","attribute12":"#","attribute15":"after","action":"PLUGIN_BE.CTB.JQ.ALV"}]}];
}
```

At the end, it appears that attribute02 is set to "#P2_TEST_ITEM," with a trailing comma. In Apex4, the selector `$("#P2_TEST_ITEM,") works, but it doesn't under Apex 5EA.

This is a jQuery change in behavior noted in: http://bugs.jquery.com/ticket/12298

I'll see if I can poke through the render.sql and come up with a patch.

**Comment by nbuytaert1** [comment]
Thanks for the explanation and pull request. The fix will be included in the next release.

You mentioned that the APEX_PLUGIN_UTIL.PAGE_ITEM_NAMES_TO_JQUERY function is available only in APEX 4.2 and later. The APEX 4.1 documentation, however, includes the function as well. So I believe we can use the PAGE_ITEM_NAMES_TO_JQUERY function without losing APEX 4.1 compatibility.

https://docs.oracle.com/html/E28475_02/apex_plugin_util.htm#BABGAJFD

Feel free to create another pull request.

Thanks again,
Nick

**Comment by cjs** [comment]
If you reopen this PR, I think we can just merge under this one.

**Comment by nbuytaert1** [comment]
Reopened issue to not forget to include the updated render function with the next release.
