### ISSUE TITLE
Select2 at Mobile Theme

### ISSUE THREAD

**Issue by sokosp** [nbuytaert1/apex-live-validation#17]
Hi Nick,
This is not a bug, but we tested it (as unsupported plugin) and it did work but didn't look very nice.

Have you tested it ? does it need any special settings/params?
Thank you again for your wonderful work, you aspire us all!

**Comment by nbuytaert1** [comment]
I think you posted this in the wrong project. This is the APEX Live Validation plugin repo.

Anyway, the Select2 APEX plugin doesn't really support the Mobile user interface. I think I tested it some years ago, but the result wasn't really satisfactory.

However, the latest versions of the Select2 jQuery plugin score better on mobile support. That's probably the reason why it's working now in APEX, but I don't know why it doesn't look nice. What exactly don't you like about it? Can you show me what's wrong with it?

Thanks,
Nick
